// A fake provider used strictly for testing our architecture
// and ensuring our routing logic works properly.

class ExampleProvider {
    constructor(browserContext) {
        this.context = browserContext;
        this.name = 'example';
    }

    async testConnection() {
        console.log(`[${this.name}] Testing connection using standard page context...`);
        // In reality, this would navigate to a protected route and 
        // check for specific DOM elements or evaluate valid tokens.
        return true;
    }

    async generateCompletion(messages, model) {
        console.log(`[${this.name}] Forwarding completion request...`);
        console.log(`Messages:`, messages);

        // Mocking latency to simulate a network call or DOM manipulation
        await new Promise(resolve => setTimeout(resolve, 800));

        // The adapter is responsible for normalizing the provider's specific
        // output format back into an OpenAI string.
        const normalizedResponse = "This is a normalized response generated by the Example Adapter.";

        return normalizedResponse;
    }
}

module.exports = ExampleProvider;
